### ISSUE TITLE
orc2dataframe limited to read of max 64mb chunk?

### ISSUE THREAD

**Issue by dselivanov** [vertica/r-dataconnector#3]
If `.orc` file is larger than 64mb, `orc2dataframe` reads only first 64mb and cuts remaining rows whithout any warnings / errors. 
I tried to look for such limits in source code, but found nothing. Mb somewhere in third-party libraries.

**Comment by dselivanov** [comment]
Probably, I missed `selectedStripes` argument. When set it properly  (`selectedStripes = "0,1"` for example), `orc2dataframe` reads whole file. 
How to set it to the total number of stripes in file?

**Comment by dselivanov** [comment]
when I call with `selectedStripes = ""`, logger produce following:

> I0119 14:33:07.220916 31861 ddc.cpp:366] url: /home/dmitry.selivanov/part-r-00000-d6ec3003-37b0-4769-a132-e67720713c2a.orc protocol:  filename: /home/dmitry.selivanov/part-r-00000-d6ec3003-37b0-4769-a132-e67720713c2a.orc ext: orc objtype: rdataframe
> I0119 14:33:07.221007 31861 ddc.cpp:380]  **selectedStripes: 0,**

which is not correct

**Comment by jorgemarsal** [comment]
You're right, there was a bug. When `selectedStripes` was empty the code incorrectly selected stripe 0 only instead of all the stripes in the file. Should work now. Can you check and close the issue if it's fixed?

**Comment by dselivanov** [comment]
Thanks for fix. I will be able to test it tomorrow.

**Comment by dselivanov** [comment]
works for now, closing...
